add_newline = true

[cmd_duration]
min_time = 5000

[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[âœ•](bold green)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""

[python]
symbol = "ğŸ"
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "â¬¢"

[rust]
symbol = "ğŸ¦€"

[zig]
symbol = "âš¡ï¸"

[dart]
symbol = "ğŸ¯"

[package]
symbol = "ğŸ“¦"
